### ISSUE TITLE
Add Crunchbase wrangling utils

### ISSUE THREAD

**Issue by beingkk** [nestauk/discovery_utils#3]
Factor out the Crunchbase wrangling utils from [here](https://github.com/nestauk/innovation_sweet_spots/blob/dev/innovation_sweet_spots/analysis/wrangling_utils.py) to this repo.

Perhaps you can do a bit of research and we can discuss on where this type of code should best be located in the repo - eg, maybe we should have a dedicated folder (eg, `src/processing` or something like that). Alternatively, maybe it can be simply kept in getters - not sure yet.

**Comment by sqr00t** [comment]
@beingkk closing this issue as linked branch covers adding the Crunchbase utils

I'm now looking into GtR and will add two further issues/branches/PRs to:
- Add GtR data pipeline(s)
- If necessary, refactor Crunchbase or other utils, looking at improving performance where possible (lower priority)
